{{- if .Values.vpn.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vpn.credentials.secretName | default "vpn-secret" }}
type: {{ .Values.vpn.credentials.type | default "Opaque" }}
data:
  password: {{ .Values.vpn.credentials.password | required "vpn.credentials.password must be defined" | b64enc }}
{{- end }}