{{- if and .Values.vpn.enabled (not .Values.vpn.provider.credentials.existingSecretName) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: vpn-config
  labels: {}
data:
  vpn_type: {{ .Values.vpn.provider.protocol }}
{{- with .Values.vpn.provider.configuration }}
{{- range $key, $value := . }}
  {{ upper $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}