{{- if and .Values.vpn.enabled (not .Values.vpn.provider.credentials.existingSecretName) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: vpn-config
  labels:
    app.kubernetes.io/name: {{ include "your-chart.name" . }}
    helm.sh/chart: {{ include "your-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  vpn_type: {{ .Values.vpn.provider.protocol }}
{{- with .Values.vpn.provider.configuration }}
{{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}