apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "qbittorrent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "qbittorrent.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qbittorrent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: {{ .Values.service.portName | default "http" }}
          containerPort: {{ .Values.service.port }}
          protocol: {{ .Values.service.protocol | default "TCP" }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
          {{- toYaml .Values.persistence.volumeMounts | nindent 12 }}
        {{- end }}
        env:
        {{- if eq .Values.vpn.provider.protocol "openvpn" }}
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: vpn-credentials
              key: OPENVPN_USER
        - name: OPENVPN_PASS
          valueFrom:
            secretKeyRef:
              name: vpn-credentials
              key: OPENVPN_PASS
        {{- else if eq .Values.vpn.provider.protocol "wireguard" }}
          - name: WIREGUARD_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: vpn-credentials
                key: WIREGUARD_PRIVATE_KEY
          - name: WIREGUARD_ADDRESSES
            valueFrom:
              secretKeyRef:
                name: vpn-credentials
                key: WIREGUARD_ADDRESSES
        {{- end }}
        {{- with .Values.env }}
        {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- if .Values.vpn.enabled }}
      - name: vpn
        image: "{{ .Values.vpn.image.repository }}:{{ .Values.vpn.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.vpn.image.pullPolicy | default "IfNotPresent" }}
        securityContext:
          {{- toYaml .Values.vpn.securityContext | nindent 12 }}
        env:
        - name: VPN_SERVICE_PROVIDER
          value: {{ .Values.vpn.provider.name }}
        {{- with .Values.vpn.env }}
        {{- toYaml . | nindent 12 }}
        {{- end }}
        envFrom:
        - secretRef:
            name: vpn-credentials
        {{- if .Values.persistence.enabled }}
        {{- with .Values.vpn.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- end }}
        {{- with .Values.vpn.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
      {{- range .Values.persistence.volumes }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .existingClaimName | default .name | required "One of name or existingClaimName must be defined" }}
      {{- end }}
      {{- range .Values.vpn.volumes }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .existingClaimName | default .name | required "One of name or existingClaimName must be defined" }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}