{{- if and .Values.vpn.enabled (not .Values.vpn.provider.credentials.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: vpn-credentials
type: Opaque
data:
  {{- if eq .Values.vpn.provider.protocol "openvpn" }}
  OPENVPN_USER: {{ .Values.vpn.provider.credentials.openvpn.username | b64enc | quote }}
  OPENVPN_PASSWORD: {{ .Values.vpn.provider.credentials.openvpn.password | b64enc | quote }}
  {{- else if eq .Values.vpn.provider.protocol "wireguard" }}
  WIREGUARD_PRIVATE_KEY: {{ .Values.vpn.provider.credentials.wireguard.privateKey | b64enc | quote }}
  {{- end }}
{{- end }}
