{{- if .Values.vpn.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: vpn-credentials
type: Opaque
data:
  {{- if eq .Values.vpn.provider.protocol "openvpn" }}
  OPENVPN_USER: {{ .Values.vpn.provider.credentials.openvpn.username | b64enc | quote }}
  OPENVPN_PASS: {{ .Values.vpn.provider.credentials.openvpn.password | b64enc | quote }}
  VPN_TYPE=openvpn
  {{- else if eq .Values.vpn.provider.protocol "wireguard" }}
  WIREGUARD_PRIVATE_KEY: {{ .Values.vpn.provider.credentials.wireguard.privateKey | b64enc | quote }}
  WIREGUARD_ADDRESSES: {{ .Values.vpn.provider.credentials.wireguard.addresses | b64enc | quote }}
  VPN_TYPE=wireguard
  {{- end }}
{{- end }}
