{{- if .Values.vpn.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: vpn-credentials
type: Opaque
data:
  {{- if eq .Values.vpn.provider.protocol "openvpn" }}
  OPENVPN_USER: {{ .Values.vpn.credentials.openvpn.username | b64enc | quote }}
  OPENVPN_PASS: {{ .Values.vpn.credentials.openvpn.password | b64enc | quote }}
  {{- else if eq .Values.vpn.provider.protocol "wireguard" }}
  WIREGUARD_PRIVATE_KEY: {{ .Values.vpn.credentials.wireguard.privateKey | b64enc | quote }}
  WIREGUARD_ADDRESSES: {{ .Values.vpn.credentials.wireguard.addresses | b64enc | quote }}
  {{- end }}
{{- end }}



vpn:
  enabled: false
  # configure your VPN here, see https://github.com/qdm12/gluetun
  provider:
    name: nordvpn
    protocol: openvpn
    openvpn:
      username: "REDACTED"
      password: "REDACTED"
    wireguard:
      privatekey: "REDACTED"
      addresses: "REDACTED"