apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudfare-tunnel.fullname" . }}
  labels:
    {{- include "cloudfare-tunnel.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cloudfare-tunnel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cloudfare-tunnel.selectorLabels" . | nindent 8 }}
    spec:
      hostNetwork: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cloudfare-tunnel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
             - cloudflared
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --protocol
            - {{ .Values.tunnel.protocol }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  {{ if .Values.tunnel.token.create }}
                  name: {{ .Release.Name }}-secret
                  key: token
                  {{ else }}
                  name: {{ .Values.tunnel.tokenSecretRef.name}}
                  key: {{ .Values.tunnel.tokenSecretRef.key}}
                  {{ end }}
            {{- if .Values.metrics.enabled }}
            - name: TUNNEL_METRICS
              value: "{{ .Values.metrics.bind_address }}:{{ .Values.metrics.port}}"
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
