{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  labels:
    app.kubernetes.io/name: {{ include "cloudfare-tunnel.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "cloudfare-tunnel.fullname" . }}
  ports:
    - name: metrics
      protocol: TCP
      port: {{ .Values.metrics.port }}
      targetPort: metrics
{{- end }}