apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2024-02-09T14:14:18Z"
  generation: 4
  labels:
    {{ .Values.metrics.prometheus_label.key }}: {{ .Values.metrics.prometheus_label.value }}
    app.kubernetes.io/managed-by: Helm
    release: promstack
  name: tunnel-metrics
spec:
  endpoints:
  - interval: 30s
    port: metrics
  namespaceSelector:
    matchNames:
    - {{ include "cloudfare-tunnel.fullname" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cloudfare-tunnel.fullname" . }}
