name: Release Charts

on:
  push:
    branches:
    - main
    - '*-wip'
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Determine Directory
      id: dir
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "dir=stable" >> $GITHUB_ENV
        else
          echo "dir=wip" >> $GITHUB_ENV
        fi
        
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        charts_dir: charts
        packages_dir: .deploy/packages
        index_dir: ${{ github.workspace }}/.deploy/${{ env.dir }}
