name: Release Charts

on:
  push:
    branches:
    - main
    - '*-wip'
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Determine Path
      id: determine-path
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "target_dir=stable" >> $GITHUB_ENV
        else
          echo "target_dir=wip" >> $GITHUB_ENV
        fi

    - name: Package Helm Charts
      run: |
        mkdir -p .deploy/${{ env.target_dir }}
        helm package charts/* --destination .deploy/${{ env.target_dir }}
        
    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.7.0
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        charts_dir: charts
        package_path: ${{ env.package_path }}
        index_dir: ${{ github.workspace }}/.deploy/${{ env.dir }}
