name: Release Charts

on:
  push:
    branches:
    - main
    - '*-wip'
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Determine Chart Version
      id: chart_version
      run: |
        if [[ $GITHUB_REF == "refs/heads/main" ]]; then
          echo "::set-output name=chart_version::$(git describe --tags --abbrev=0)"
        else
          echo "::set-output name=chart_version::$(git describe --tags --abbrev=0)-wip-$(date +%Y%m%d%H%M%S)"
        fi

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        CHART_VERSION: ${{ steps.chart_version.outputs.chart_version }}