name: Release Charts

on:
  push:
    branches:
    - main
    - '*-wip'
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Determine Path
      id: determine-path
      run: |
        if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
          echo "target_dir=." >> $GITHUB_ENV
        else
          echo "target_dir=wip" >> $GITHUB_ENV
        fi

    - name: Package Helm Charts
      run: |
        mkdir -p .deploy/${{ env.target_dir }}
        helm package charts/* --destination .deploy/${{ env.target_dir }}

    - name: Update gh-pages
      run: |
        git fetch origin gh-pages
        git checkout gh-pages || git checkout --orphan gh-pages
        mkdir -p ./${{ env.target_dir }}

        # Move packaged charts to the determined directory
        mv .deploy/${{ env.target_dir }}/*.tgz ./${{ env.target_dir }}/

        # Update the helm index in the specified directory
        helm repo index ./${{ env.target_dir }} --url https://thurcombe.github.io/nullpacket-charts/${{ env.target_dir }}

        git add ./${{ env.target_dir }}/*.tgz ./${{ env.target_dir }}/index.yaml
        git commit -m "Update charts for ${{ github.ref }}"
        git push origin gh-pages